package com.juls.firstapp.librarymanagementsystem.model.enums;

public enum Genre {
        TEXTBOOK,
        REFERENCE_BOOK,
        SCIENCE,
        MATHEMATICS,
        ENGINEERING,
        MEDICINE,
        PSYCHOLOGY,
        SOCIOLOGY,
        POLITICAL_SCIENCE,
        ECONOMICS,
        HISTORY,
        PHILOSOPHY,
        LAW,
        EDUCATION_AND_TEACHING,
        COMPUTER_SCIENCE,
        ENVIRONMENTAL_SCIENCE,
        LITERATURE_AND_LANGUAGE,
        ART_AND_ART_HISTORY,
        ANTHROPOLOGY,
        FICTION,
        DYSTOPIAN,
        CLASSIC,
        ROMANCE,
        COMING_OF_AGE,
        FANTASY,
        SCIENCE_FICTION,
        GOTHIC,
        HISTORICAL,
        ADVENTURE,
        BUSINESS_AND_MANAGEMENT;
}
